name: Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source/

    strategy:
      matrix:
        compiler: [gcc-10]

    env:
      MODE: "dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++
        uses: actions/setup-cpp@v2
        with:
          compiler: gcc-10

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./run_tests
